export const data = [
  {
    image_url: "",
    title_en: "vans",
    title_ar: "عربات",
    price: 20,
    currency_en: "AED",
    currency_ar: "درهم",
  },
  {
    image_url: "",
    title_en: "Addidas",
    title_ar: "شركة اديداس",
    price: 30,
    currency_en: "AED",
    currency_ar: "درهم",
  },
  {
    image_url: "",
    title_en: "Nike",
    title_ar: "نايك",
    price: 40,
    currency_en: "AED",
    currency_ar: "درهم",
  },
  {
    image_url: "",
    title_en: "Kids",
    title_ar: "أطفال",
    price: 20,
    currency_en: "AED",
    currency_ar: "درهم",
  },
  {
    image_url: "",
    title_en: "Women",
    title_ar: "نساء",
    price: 20,
    currency_en: "AED",
    currency_ar: "درهم",
  },
  {
    image_url: "",
    title_en: "Men",
    title_ar: "رجال",
    price: 20,
    currency_en: "AED",
    currency_ar: "درهم",
  },
];
